name: Alchemist
main: com.ivalicemud.alchemist.Alchemist
version: 1.1.3
description: Alchemist - Change your potions!
author: raum266
 
commands:
   alchemist:
      aliases: [alch, alchemy]
      description: Main commands for the alchemist plugin
      usage: /alchemist <options> - use /alchemist help for a list of options.
      
permissions:
   alchemist.admin:
      description: Gives access to all permission nodes in Alchemist
      default: op
